/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../src/components/app-provider/app-provider.vue')['default']
    AsyncSelect: typeof import('./../src/components/search-form/async-select.vue')['default']
    CommonTable: typeof import('./../src/components/common-table/common-table.vue')['default']
    CommonTableHeader: typeof import('./../src/components/common-table-header/common-table-header.vue')['default']
    IconButton: typeof import('./../src/components/icon-button/icon-button.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NcButton: typeof import('./../src/components/nc-button/nc-button.vue')['default']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NWatermark: typeof import('naive-ui')['NWatermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../src/components/search-form/search-form.vue')['default']
    SliderVerify: typeof import('./../src/components/slider-verify/slider-verify.vue')['default']
    SvgIcon: typeof import('./../src/components/svg-icon/svg-icon.vue')['default']
    TableColumn: typeof import('./../src/components/common-table/table-column.vue')['default']
  }
}

// For TSX support
declare global {
  const AppProvider: typeof import('./../src/components/app-provider/app-provider.vue')['default']
  const AsyncSelect: typeof import('./../src/components/search-form/async-select.vue')['default']
  const CommonTable: typeof import('./../src/components/common-table/common-table.vue')['default']
  const CommonTableHeader: typeof import('./../src/components/common-table-header/common-table-header.vue')['default']
  const IconButton: typeof import('./../src/components/icon-button/icon-button.vue')['default']
  const NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
  const NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NcButton: typeof import('./../src/components/nc-button/nc-button.vue')['default']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDataTable: typeof import('naive-ui')['NDataTable']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGrid: typeof import('naive-ui')['NGrid']
  const NGridItem: typeof import('naive-ui')['NGridItem']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NInput: typeof import('naive-ui')['NInput']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NPopover: typeof import('naive-ui')['NPopover']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const NWatermark: typeof import('naive-ui')['NWatermark']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchForm: typeof import('./../src/components/search-form/search-form.vue')['default']
  const SliderVerify: typeof import('./../src/components/slider-verify/slider-verify.vue')['default']
  const SvgIcon: typeof import('./../src/components/svg-icon/svg-icon.vue')['default']
  const TableColumn: typeof import('./../src/components/common-table/table-column.vue')['default']
}